### ISSUE TITLE
Large Files are not accessible

### ISSUE THREAD

**Issue by decanbay** [haeriamin/Subspace-Graph-Physics#1]
Hello, I was trying to replicate your results but the eigenvector files are not downloadable or sizes below 1kb when downloaded. 

This is the response from git LFS

> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. Failed to fetch some objects from 'https://github.com/haeriamin/Subspace-Graph-Physics.git/info/lfs'

**Comment by haeriamin** [comment]
Hi @decanbay, thanks for your interest. Please find the files here:

https://drive.google.com/drive/folders/1aFfnAy2HBoyNnsd6O3ZfZaACXJpUMllm?usp=sharing

**Comment by decanbay** [comment]
Thank you!
